# Generated by Django 4.2 on 2023-04-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='true', max_length=200, null='true')),
                ('price', models.FloatField(null='true')),
            ],
        ),
    ]
